language: generic 
sudo: required
services:
  - docker

before_install: 
  -docker build -t antonkbr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antonkbr/docker-react yarn run test